setting:
  delayTime: 2000
users:
# 用户1
  - 
    # SEU健康打卡模块
    SEU:
      active: false
      username: 
      password: 
    lesson:
      active: false
      openid: 
# 用户2
  - 
    # SEU健康打卡模块
    SEU:
      active: false
      username: 
      password:
    lesson:
      active: false
      openid: 